create table t_folder (
pk_id bigint generated by default as identity (start with 1),
asked_amount int,
debt_amount int,
id varchar2(40 char),
payed_amount int,
provisioned_amount int,
primary key (pk_id)
);

create table t_folder_affiliate (
fk_folder bigint not null,
customer_id varchar2(40 char),
primary_debtor boolean
);

create table t_folder_ticket (
fk_folder bigint not null,
ticket varchar2(40 char)
);

create table t_debt (
pk_id bigint generated by default as identity (start with 1),
amount int,
cart_amount int,
cart_id varchar2(40 char),
delay_date date,
delay_day_count int,
discount_rate int,
folder_id varchar2(40 char),
id varchar2(40 char),
notes varchar2(100 char),
payed_amount int,
status varchar2(20 char),
tax_rate int,
primary key (pk_id)
);

create table t_debt_recall (
fk_debt bigint not null,
amount int,
date date
);

create table t_debt_payment (
fk_debt bigint not null,
amount int,
date date,
ticket varchar2(40, char)
);


alter table t_debt_payment
add constraint FK6t9g0llwfr3hc3hr1lx5v9bdf
foreign key (fk_debt)
references t_debt;

alter table t_debt_recall
add constraint FKexygo2gag4aiy6wy7po6cop2x
foreign key (fk_debt)
references t_debt;

alter table t_folder_affiliate
add constraint FKdjx7mst4l2rsi7ygc5p5y7in5
foreign key (fk_folder)
references t_folder;

alter table t_folder_ticket
add constraint FKsdv4f09sddwgh2vbjbiyxjknu
foreign key (fk_folder)
references t_folder;

