create table t_folder (
pk_id bigint generated by default as identity (start with 1),
asked_amount varchar(255),
debt_amount varchar(255),
id varchar(255),
payed_amount varchar(255),
provisioned_amount varchar(255),
primary key (pk_id)
);

create table t_folder_affiliate (
fk_folder bigint not null,
customer_id varchar(255),
primary_debtor boolean
);

create table t_folder_ticket (
fk_folder bigint not null,
tickets varchar(255)
);

create table t_debt (
pk_id bigint generated by default as identity (start with 1),
amount varchar(255),
cart_amount varchar(255),
cart_id varbinary(255),
delay_date date,
delay_day_count integer,
discount_rate varchar(255),
folder_id varchar(255),
id varchar(255),
notes varchar(255),
payed_amount varchar(255),
status varchar(255),
tax_rate varchar(255),
primary key (pk_id)
);

create table t_debt_recall (
fk_debt bigint not null,
amount bigint,
date date
);

create table t_debt_payment (
fk_debt bigint not null,
amount bigint,
date date,
ticket varchar(255)
);


alter table t_debt_payment
add constraint FK6t9g0llwfr3hc3hr1lx5v9bdf
foreign key (fk_debt)
references t_debt;

alter table t_debt_recall
add constraint FKexygo2gag4aiy6wy7po6cop2x
foreign key (fk_debt)
references t_debt;

alter table t_folder_affiliate
add constraint FKdjx7mst4l2rsi7ygc5p5y7in5
foreign key (fk_folder)
references t_folder;

alter table t_folder_ticket
add constraint FKsdv4f09sddwgh2vbjbiyxjknu
foreign key (fk_folder)
references t_folder;

